server:
  port: 8080
  context-path: /api
#
#spring:
#  application:
#    name: gateway
#  cloud:
#    consul:
#      host: consul
#      port: 8500
#      discovery:
#        health-check-path: /api/health
#        instanceId: ${spring.application.name}:${random.int}

user-service:
  ribbon:
    listOfServers: localhost:8081

todo-service:
  ribbon:
    listOfServers: localhost:8082

zuul:
  sensitiveHeaders:
  routes:
    register-service:
      path: /users
      serviceId: user-service
      strip-prefix: false
    todo-service:
      path: /todos
      serviceId: todo-service
      strip-prefix: false

logging:
  level:
    org:
      springframework:
        cloud:
          netflix: TRACE